version: "3"

services:

  postgres:
    image: postgres:13
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - stealth-database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet
    hostname: postgres
    container_name: postgres

  pgadmin:
    image: dpage/pgadmin4:5.7
    env_file:
      - ./server/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - appnet
    hostname: pgadmin
    container_name: pgadmin

networks:
  appnet:
    driver: bridge

volumes:
  stealth-database-data:
  pgadmin-data:



